### ISSUE TITLE
Link to Ganar's caves system mentioned

### ISSUE THREAD

**Issue by Oranamous** [TheForsakenFurby/Surface-Rules-Guide-Minecraft-JE-1.18#1]
I was hoping to see some of Ganar's work as you mentioned they made nice caves using the surface rules, however I could not find it after searching, so I was hoping you could link it if possible.

Thanks in advance - Oranamous

**Comment by TheForsakenFurby** [comment]
Hi! Sorry for the late response. There's no datapack released with the custom caves (yet), but there's a few screenshots and an explanation in the Minecraft Configs discord server.

This link should work for the next 7 days if you'd like to join: https://discord.gg/5ZJqgPk7

Once there, you should be able to access a thread called "Surface rule noise caves" in the #screenshots channel, which contains a screenshot and some of the code. (You could also search for messages from Ganar in December, 2021 to see a lot more screenshots.)

No worries if you don't join, and good luck with the worldgen!

**Comment by Oranamous** [comment]
Alright, thanks!

**Comment by TheBrewingMiner** [comment]
Hi! I am also looking for Ganar's work, particularly on the custom ore veins. I can't find the discord server you mentioned, and hope that you could link me to it?

Thanks,
TBM

**Comment by TheForsakenFurby** [comment]
Sure! Sorry for the late response. Here's a 7-day link: https://discord.gg/c6NW9vSK
